/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


// Class Restaurant constructor test
    class RestaurantTest {
        @Test
        void restaurantConstructorTest() {
            Restaurant restTest = new Restaurant("Papi", 3);
            assertEquals(restTest.getName(), "Papi");
        }

        @Test
        void restaurantRatingReturnsString() {
            Restaurant restTest = new Restaurant("Burgerize", 3);
            assertEquals(restTest.getPrice(), 3);
        }
    }

    // Class Review constructor test
    class ReviewTest {
        @Test
        void reviewConstructorTest() {
            Review restTest = new Review("A review", "Hashem Smadi", 3);
            assertEquals(restTest.getAuthor(), "Hashem Smadi");
        }

        @Test
        void reviewReturnsString() {
            Review restTest = new Review("I love it!!!", "Hashem Smadi", 4);
            assertEquals(restTest.toString(), "Author's name is Hashem Smadi, He review this place with (****) star rating, and he said \" I love it!!! \"");
        }
    }

    // add review to restaurant test
    class addReviewTest {
        @Test
        void addTest() {
            Restaurant revTest = new Restaurant("Popeyes", 2);
            revTest.addReview("a", "Hashem", 5);
            revTest.addReview("g", "Hashem", 4);
            revTest.addReview("Bad", "Hashem", 3);
            assertEquals(revTest.getRating(), 5);
        }

    }






