/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.lang.reflect.Array;
import java.util.ArrayList;

// Class Restaurant constructor test
    class RestaurantTest {
        @Test
        void restaurantConstructorTest() {
            Restaurant restTest = new Restaurant("Papi", 3);
            assertEquals(restTest.getName(), "Papi");
        }

        @Test
        void restaurantRatingReturnsString() {
            Restaurant restTest = new Restaurant("Burgerize", 3);
            assertEquals(restTest.getPrice(), 3);
        }
    }

    // Class Review constructor test
    class ReviewTest {
        @Test
        void reviewConstructorTest() {
            Review restTest = new Review("A review", "Hashem Smadi", 3);
            assertEquals(restTest.getAuthor(), "Hashem Smadi");
        }

        @Test
        void reviewReturnsString() {
            Review restTest = new Review("I love it!!!", "Hashem Smadi", 4);
            assertEquals(restTest.toString(), "Author's name is Hashem Smadi, He review this place with (****) star rating, and he said \" I love it!!! \"");
        }
    }

    // add review to restaurant test
    class addReviewTest {
        @Test
        void addTest() {
            Restaurant revTest = new Restaurant("Popeyes", 2);
            revTest.addReview("a", "Hashem", 5);
            revTest.addReview("g", "Hashem", 4);
            revTest.addReview("Bad", "Hashem", 3);
            assertEquals(revTest.getRating(), 5);
        }

    }
// test shop constructor
class shopTest {
    @Test
    void shopToStringTest() {
        Shop shopTest = new Shop("PizzaHut", "Bad", 3);
        assertEquals(shopTest.toString(), "the review to PizzaHut is Bad");
    }
}

// add review to shop test
class addReviewShopTest{
    @Test
    void addTest() {
        Shop revTest = new Shop("Popeyes","Hashem", 2);
        revTest.addReview("g", "Hashem", 4);
        revTest.addReview("a", "Hashem", 5);
        revTest.addReview("Bad", "Hashem", 3);
        assertEquals(revTest.getShopRating(), (4));
    }
}
class addReviewTheaterTest{
    @Test
    void addTest() {
        ArrayList movies = new ArrayList();
        movies.add("the GodFather");
        movies.add("requiem for a dream");
        Theater revTest = new Theater("Cinema",movies);
        revTest.addReview("Bad", "Hashem", 3);
        revTest.addReview("a", "Hashem", 5);
        revTest.addReview("g", "Hashem", 4);
        revTest.addMovie("taxi driver");
        ArrayList<String> y = new ArrayList<>();
        y.add("the GodFather");
        y.add("requiem for a dream");
        y.add("taxi driver");
        assertEquals(revTest.getMovies(), y);
    }
}





